name: Tests
on: [push, pull_request]


jobs:
  build:
    name: ${{ matrix.os }} / ${{ matrix.golang-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [Ubuntu, MacOS, Windows]
        golang-version: [1.14.15, 1.15.12]
    steps:
    - run: |
        echo "/home/runner/.pyenv/bin" >> $GITHUB_PATH
        echo "/home/runner/.local/bin" >> $GITHUB_PATH
    - uses: actions/checkout@v2
    - name: Set up Go ${{ matrix.golang-version }}
      uses: actions/setup-go@v2
      id: setup-go
      with:
        go-version: ${{ matrix.golang-version }}
    - name: Install Go Modules
      run: |
        go get github.com/piquette/finance-go
        go get -u golang.org/x/lint/golint
    - name: Run Go tests
      run: |
        go test -v -cover ./...
    - name: Run Go linter
      run: |
        golint ./...
    - name: Set up Python environment
      run: |
        curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
        pyenv install 3.6.3
        echo "eval '$(pyenv init -)'" >> ~/.bashrc
        eval "$(pyenv virtualenv-init -)" >> ~/.bashrc
        source ~/.bashrc
        pyenv global 3.6.3
        pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
    - name: Lint with pylint
      run: |
        pipenv run pylint termfrequency
      #continue-on-error: true
    - name: Lint with flake8
      run: |
        pipenv run flake8 termfrequency
      #continue-on-error: true
